require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');
const Quiz = require('../models/Quiz');
const Mission = require('../models/Mission');
const { Badge, Challenge } = require('../models/GameModels');

const badges = [
  { name: 'Welcome Sprout', description: 'Join the EcoQuest community', icon: '🌱', category: 'milestone', requirement: { type: 'register', value: 0 }, rarity: 'common', xpBonus: 10 },
  { name: 'First Steps', description: 'Complete your first quiz', icon: '👣', category: 'quiz', requirement: { type: 'quizzes', value: 1 }, rarity: 'common', xpBonus: 20 },
  { name: 'Knowledge Seeker', description: 'Complete 5 quizzes', icon: '📚', category: 'quiz', requirement: { type: 'quizzes', value: 5 }, rarity: 'common', xpBonus: 50 },
  { name: 'Quiz Master', description: 'Complete 20 quizzes', icon: '🎓', category: 'quiz', requirement: { type: 'quizzes', value: 20 }, rarity: 'rare', xpBonus: 150 },
  { name: 'Eco Warrior', description: 'Reach 500 XP', icon: '⚔️', category: 'milestone', requirement: { type: 'xp', value: 500 }, rarity: 'rare', xpBonus: 75 },
  { name: 'Green Guardian', description: 'Reach Level 5', icon: '🛡️', category: 'milestone', requirement: { type: 'level', value: 5 }, rarity: 'epic', xpBonus: 200 },
  { name: 'Streak Starter', description: 'Maintain a 3-day streak', icon: '🔥', category: 'streak', requirement: { type: 'streak', value: 3 }, rarity: 'common', xpBonus: 30 },
  { name: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '💪', category: 'streak', requirement: { type: 'streak', value: 7 }, rarity: 'rare', xpBonus: 100 },
  { name: 'Challenge Champion', description: 'Complete 10 challenges', icon: '🏆', category: 'challenge', requirement: { type: 'challenges', value: 10 }, rarity: 'epic', xpBonus: 250 },
  { name: 'Planet Protector', description: 'Reach 2000 XP', icon: '🌍', category: 'milestone', requirement: { type: 'xp', value: 2000 }, rarity: 'legendary', xpBonus: 500 },
];

// ─────────────────────────────────────────────────────────────────────────────
// SCHOOL STUDENT QUIZZES — 10 questions each, easy & basic level
// ─────────────────────────────────────────────────────────────────────────────
const schoolQuizzes = [
  {
    title: 'What is Climate Change? (School)',
    description: 'A fun introduction to climate change for school students — simple and easy!',
    topic: 'climateChange', difficulty: 'beginner', thumbnail: '🌡️',
    xpReward: 60, timeLimit: 480, targetAudience: 'School Student',
    questions: [
      { question: 'What makes Earth warm like a blanket?', options: ['The sun alone','Greenhouse gases trapping heat','The moon\'s light','Wind'], correctAnswer: 1, explanation: 'Greenhouse gases like CO₂ act like a blanket around Earth, trapping the sun\'s heat.', points: 10 },
      { question: 'Which gas do cars and factories release that causes global warming?', options: ['Oxygen','Carbon Dioxide (CO₂)','Nitrogen','Water vapour'], correctAnswer: 1, explanation: 'Cars and factories burn fossil fuels and release CO₂, a major greenhouse gas.', points: 10 },
      { question: 'What happens to ice at the North and South Poles when Earth gets warmer?', options: ['It grows bigger','It stays the same','It melts','It changes colour'], correctAnswer: 2, explanation: 'Warming temperatures cause polar ice to melt, raising sea levels.', points: 10 },
      { question: 'Which of these is NOT a way students can help fight climate change?', options: ['Switching off lights','Planting trees','Wasting water','Using less plastic'], correctAnswer: 2, explanation: 'Wasting water wastes energy too. Saving water helps reduce carbon emissions.', points: 10 },
      { question: 'What is "global warming"?', options: ['The world getting colder','A type of earthquake','The slow rise in Earth\'s temperature','A new video game'], correctAnswer: 2, explanation: 'Global warming is the long-term rise in Earth\'s average temperature due to human activities.', points: 10 },
      { question: 'Where does most of the extra heat causing global warming come from?', options: ['Volcanoes','Burning coal, oil and gas','The sun getting brighter','Forests'], correctAnswer: 1, explanation: 'Burning fossil fuels like coal, oil, and gas releases CO₂ and causes most of the warming.', points: 10 },
      { question: 'True or False: Climate change can cause more extreme weather like floods and droughts.', options: ['True','False'], correctAnswer: 0, explanation: 'Climate change makes extreme weather events like floods, droughts and storms more frequent.', points: 10 },
      { question: 'What simple action at home saves energy and reduces CO₂?', options: ['Leaving lights on all day','Taking very long showers','Turning off appliances when not in use','Keeping windows open in winter'], correctAnswer: 2, explanation: 'Turning off unused appliances saves electricity, reducing CO₂ emissions from power plants.', points: 10 },
      { question: 'Which of these is a renewable (clean) energy source?', options: ['Coal','Petrol','Solar power','Diesel'], correctAnswer: 2, explanation: 'Solar power comes from the sun and produces no harmful gases — it\'s clean and renewable.', points: 10 },
      { question: 'What agreement did countries sign to try to stop climate change together?', options: ['The Plastic Treaty','The Paris Agreement','The Green Law','The Air Act'], correctAnswer: 1, explanation: 'The Paris Agreement (2015) is a global plan where countries commit to reducing emissions.', points: 10 },
    ],
  },
  {
    title: 'Recycling at School (School)',
    description: 'Learn how to recycle and reduce waste in your daily school life',
    topic: 'recycling', difficulty: 'beginner', thumbnail: '♻️',
    xpReward: 55, timeLimit: 480, targetAudience: 'School Student',
    questions: [
      { question: 'What does the recycling symbol (three arrows in a triangle) mean?', options: ['Throw it away','This item can be recycled','Danger: toxic','Do not open'], correctAnswer: 1, explanation: 'The three-arrow triangle means the material can be recycled and made into something new.', points: 10 },
      { question: 'Which bin should you put a clean plastic water bottle in?', options: ['Food waste bin','Recycling bin','General rubbish bin','Compost bin'], correctAnswer: 1, explanation: 'Clean plastic bottles belong in the recycling bin so they can be recycled.', points: 10 },
      { question: 'What can you do with old newspapers instead of throwing them away?', options: ['Burn them','Use for art projects or recycle them','Leave them in the park','Put them down the drain'], correctAnswer: 1, explanation: 'Paper can be recycled many times or creatively reused for school projects.', points: 10 },
      { question: 'True or False: Food scraps can be turned into compost for plants.', options: ['True','False','Only sometimes','Only in factories'], correctAnswer: 0, explanation: 'Composting food scraps creates rich fertilizer that helps plants grow.', points: 10 },
      { question: 'What is the first rule of the "3 Rs" of waste reduction?', options: ['Recycle','Reuse','Reduce','Remove'], correctAnswer: 2, explanation: '"Reduce" comes first — the best way to deal with waste is to produce less of it.', points: 10 },
      { question: 'How long can a plastic bag take to break down in nature?', options: ['1 year','10 years','Up to 1,000 years','1 week'], correctAnswer: 2, explanation: 'Plastic bags can take up to 1,000 years to decompose, polluting the environment for generations.', points: 10 },
      { question: 'Which of these is an example of "reusing" something?', options: ['Throwing away a glass jar','Using an old jar as a pencil holder','Buying a new plastic bag every time','Putting food in a bin'], correctAnswer: 1, explanation: 'Reusing means giving items a second life, like using old jars as storage containers.', points: 10 },
      { question: 'Why should you rinse food containers before recycling them?', options: ['To make them look nice','To remove food waste that can contaminate recyclables','To make them lighter','No reason needed'], correctAnswer: 1, explanation: 'Dirty containers with food residue can contaminate whole batches of recyclables, making them unrecyclable.', points: 10 },
      { question: 'What is e-waste?', options: ['Energy waste from factories','Old or broken electronic devices like phones and laptops','Edible waste from restaurants','Environmental waste water'], correctAnswer: 1, explanation: 'E-waste is discarded electronic equipment. It must be properly recycled to avoid toxic chemicals entering the environment.', points: 10 },
      { question: 'Which of these is NOT recyclable in most places?', options: ['Cardboard boxes','Aluminium cans','Greasy pizza boxes','Glass bottles'], correctAnswer: 2, explanation: 'Greasy pizza boxes contaminate paper recycling. The clean parts can be torn off and recycled.', points: 10 },
    ],
  },
  {
    title: 'Animals & Nature Around Us (School)',
    description: 'Fun facts about animals, plants, and why we need to protect nature',
    topic: 'biodiversity', difficulty: 'beginner', thumbnail: '🦁',
    xpReward: 55, timeLimit: 480, targetAudience: 'School Student',
    questions: [
      { question: 'What do bees do that helps flowers and plants grow?', options: ['Eat them','Pollinate them by carrying pollen','Water them','Scare other insects away'], correctAnswer: 1, explanation: 'Bees carry pollen between flowers, helping plants reproduce — called pollination.', points: 10 },
      { question: 'What does "endangered" mean for an animal?', options: ['It is dangerous','It is very small','It is at risk of dying out completely','It lives in danger zones'], correctAnswer: 2, explanation: 'Endangered animals are at serious risk of becoming extinct if we do not protect them.', points: 10 },
      { question: 'Which of these actions helps protect wildlife habitats?', options: ['Cutting down forests','Planting more trees','Building more roads in forests','Throwing rubbish in rivers'], correctAnswer: 1, explanation: 'Planting trees helps rebuild habitats that animals need to survive.', points: 10 },
      { question: 'Why is the rainforest called the "lungs of the Earth"?', options: ['Because it is very hot','Because it breathes at night','Because it produces much of Earth\'s oxygen','Because it is full of animals'], correctAnswer: 2, explanation: 'Rainforests absorb CO₂ and release oxygen, much like our lungs breathe for us.', points: 10 },
      { question: 'What is a food chain?', options: ['A chain of restaurants','How energy passes from plants to animals to other animals','A type of fence in farms','A way animals communicate'], correctAnswer: 1, explanation: 'A food chain shows how energy moves through nature: plants → herbivores → carnivores.', points: 10 },
      { question: 'What is the biggest threat to most wild animals today?', options: ['Too much food','Habitat destruction','Other animals','Too much rain'], correctAnswer: 1, explanation: 'Habitat destruction (clearing forests and wetlands) is the leading cause of wildlife decline worldwide.', points: 10 },
      { question: 'True or False: Tigers are an endangered species.', options: ['True','False'], correctAnswer: 0, explanation: 'Tigers are endangered with fewer than 4,000 left in the wild due to poaching and habitat loss.', points: 10 },
      { question: 'What do earthworms do for soil?', options: ['Make soil dry','Make soil salty','Improve soil health by loosening and enriching it','Poison plants'], correctAnswer: 2, explanation: 'Earthworms tunnel through soil, improving drainage, aeration, and adding nutrients through their waste.', points: 10 },
      { question: 'Which of these is a herbivore (plant-eater)?', options: ['Lion','Eagle','Cow','Shark'], correctAnswer: 2, explanation: 'Cows are herbivores — they eat grass and plants only.', points: 10 },
      { question: 'What is "extinction"?', options: ['An animal sleeping for a long time','A species dying out completely forever','Animals moving to new places','Animals changing colour'], correctAnswer: 1, explanation: 'Extinction means a species has completely disappeared from Earth and can never return.', points: 10 },
    ],
  },
  {
    title: 'Our Oceans & Water (School)',
    description: 'Discover the importance of water and how to keep our oceans and rivers clean',
    topic: 'oceanHealth', difficulty: 'beginner', thumbnail: '🌊',
    xpReward: 55, timeLimit: 480, targetAudience: 'School Student',
    questions: [
      { question: 'How much of Earth\'s surface is covered by water?', options: ['About 30%','About 50%','About 70%','About 90%'], correctAnswer: 2, explanation: 'About 71% of Earth\'s surface is covered by water, mostly oceans.', points: 10 },
      { question: 'What happens when plastic gets into the ocean?', options: ['It dissolves quickly','Fish and sea animals can swallow it and get hurt','It helps coral reefs grow','It disappears in sunlight'], correctAnswer: 1, explanation: 'Plastic in oceans breaks into microplastics and harms marine animals who mistake it for food.', points: 10 },
      { question: 'Which of these is the best way to keep water clean?', options: ['Throw rubbish near rivers','Pour chemicals down drains','Never litter and use less plastic','Use more plastic bags'], correctAnswer: 2, explanation: 'Not littering and reducing plastic use prevents waste from reaching our waterways.', points: 10 },
      { question: 'What are coral reefs often called?', options: ['Rainforests of the sea','Deserts of the sea','Mountains of the sea','Forests of the land'], correctAnswer: 0, explanation: 'Coral reefs are called "rainforests of the sea" because they support thousands of species.', points: 10 },
      { question: 'True or False: We can drink water directly from the ocean.', options: ['True','False'], correctAnswer: 1, explanation: 'Ocean water is too salty to drink. It needs to be desalinated before humans can drink it.', points: 10 },
      { question: 'What percentage of Earth\'s water is fresh water that we can drink?', options: ['About 70%','About 30%','About 10%','About 3%'], correctAnswer: 3, explanation: 'Only about 3% of Earth\'s water is fresh water, and most of that is frozen in glaciers.', points: 10 },
      { question: 'Which animal is most harmed by plastic bags in the ocean?', options: ['Dolphins','Sea turtles','Sharks','Crabs'], correctAnswer: 1, explanation: 'Sea turtles often mistake plastic bags for jellyfish and eat them, which can be fatal.', points: 10 },
      { question: 'What causes coral bleaching?', options: ['Too much rain','Warmer ocean temperatures','Cold water currents','Underwater earthquakes'], correctAnswer: 1, explanation: 'When oceans warm up, corals expel the algae that give them colour — this is called bleaching.', points: 10 },
      { question: 'How much water can you save by turning off the tap while brushing teeth?', options: ['1 litre','6 litres per minute','100 litres','No difference'], correctAnswer: 1, explanation: 'A running tap uses about 6 litres per minute. Turning it off while brushing saves significant water.', points: 10 },
      { question: 'What is the Great Pacific Garbage Patch?', options: ['A beautiful island in the Pacific','A huge area of plastic waste floating in the ocean','An underwater volcano','A coral reef in the Pacific Ocean'], correctAnswer: 1, explanation: 'It\'s a vast area of plastic waste, mostly microplastics, swirling in the North Pacific Ocean.', points: 10 },
    ],
  },
  {
    title: 'Clean Energy for Kids (School)',
    description: 'Learn about solar, wind and other clean energy sources in a fun easy way',
    topic: 'renewableEnergy', difficulty: 'beginner', thumbnail: '🌞',
    xpReward: 55, timeLimit: 480, targetAudience: 'School Student',
    questions: [
      { question: 'What is solar energy?', options: ['Energy from the wind','Energy from the sun','Energy from water','Energy from coal'], correctAnswer: 1, explanation: 'Solar energy comes from sunlight and is captured using solar panels.', points: 10 },
      { question: 'Which of these is a renewable (never runs out) energy source?', options: ['Coal','Oil','Natural gas','Wind'], correctAnswer: 3, explanation: 'Wind is a renewable energy source — it never runs out unlike fossil fuels.', points: 10 },
      { question: 'What do solar panels do?', options: ['Heat water only','Convert sunlight into electricity','Store wind energy','Power only large factories'], correctAnswer: 1, explanation: 'Solar panels contain cells that convert sunlight directly into electricity.', points: 10 },
      { question: 'Why is burning coal bad for the environment?', options: ['It is too expensive','It releases pollution and CO₂ into the air','It makes too much electricity','It is hard to find'], correctAnswer: 1, explanation: 'Burning coal releases CO₂ and harmful pollutants causing air pollution and climate change.', points: 10 },
      { question: 'Where would you most likely see wind turbines?', options: ['Inside shopping malls','On tall windy hills or offshore','Underground','Inside schools'], correctAnswer: 1, explanation: 'Wind turbines are placed in windy locations like hilltops and offshore to generate electricity.', points: 10 },
      { question: 'What does a wind turbine look like?', options: ['A large fan with spinning blades','A big black panel on a roof','A dam on a river','A tall chimney'], correctAnswer: 0, explanation: 'Wind turbines have large blades that spin in the wind, generating electricity from the motion.', points: 10 },
      { question: 'True or False: Solar panels work even on cloudy days.', options: ['True','False'], correctAnswer: 0, explanation: 'Solar panels still generate electricity on cloudy days, just less than on sunny days.', points: 10 },
      { question: 'What is hydropower?', options: ['Energy from hydrogen gas','Electricity generated from moving water','Solar energy stored in water','Wind energy near the coast'], correctAnswer: 1, explanation: 'Hydropower generates electricity using the force of moving or falling water, like in a dam.', points: 10 },
      { question: 'Which of these uses the least energy in a home?', options: ['An old incandescent bulb','An LED bulb','A fluorescent tube','A halogen lamp'], correctAnswer: 1, explanation: 'LED bulbs use up to 80% less energy than traditional incandescent bulbs.', points: 10 },
      { question: 'What is a major advantage of renewable energy over fossil fuels?', options: ['It is always cheaper','It produces no harmful greenhouse gases','It works even without sunlight or wind','It is easier to transport'], correctAnswer: 1, explanation: 'Renewable energy sources like solar and wind produce no CO₂ or harmful pollutants during generation.', points: 10 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COLLEGE STUDENT QUIZZES — 20 questions each, moderate & analytical level
// ─────────────────────────────────────────────────────────────────────────────
const collegeQuizzes = [
  {
    title: 'Climate Systems & Policy (College)',
    description: 'Comprehensive coverage of climate science, carbon cycles, IPCC findings and international policy',
    topic: 'climateChange', difficulty: 'intermediate', thumbnail: '🌡️',
    xpReward: 100, timeLimit: 900, targetAudience: 'College Student',
    questions: [
      { question: 'What is "radiative forcing" in climate science?', options: ['Wind force on solar panels','Net change in energy flux caused by a climate driver','Rate at which glaciers melt','Reflectivity of Earth\'s surface'], correctAnswer: 1, explanation: 'Radiative forcing measures how much a factor (like CO₂) changes the energy balance of Earth\'s atmosphere.', points: 10 },
      { question: 'Which feedback loop accelerates warming by reducing Earth\'s reflectivity as ice melts?', options: ['Carbon cycle feedback','Ice-albedo feedback','Water vapour feedback','Methane clathrate feedback'], correctAnswer: 1, explanation: 'As ice melts, darker ocean/land absorbs more heat instead of reflecting it, creating a positive feedback.', points: 10 },
      { question: 'According to IPCC AR6, what temperature rise is considered a critical tipping point?', options: ['0.5°C above pre-industrial','1.5°C above pre-industrial','3°C above pre-industrial','5°C above pre-industrial'], correctAnswer: 1, explanation: 'IPCC AR6 identifies 1.5°C as key — beyond this, severe and irreversible impacts increase significantly.', points: 10 },
      { question: 'What is the global warming potential (GWP) of methane compared to CO₂ over 100 years?', options: ['About 5x','About 15x','About 28-34x','About 100x'], correctAnswer: 2, explanation: 'Methane has a GWP of approximately 28-34 times that of CO₂ over a 100-year time horizon.', points: 10 },
      { question: 'What is a "carbon sink"?', options: ['A device that captures CO₂ from factories','Any system that absorbs more carbon than it releases','Underground oil reserves','A type of carbon tax policy'], correctAnswer: 1, explanation: 'Carbon sinks (forests, oceans, soil) absorb more CO₂ than they emit, regulating the climate.', points: 10 },
      { question: 'What does "net-zero emissions" mean?', options: ['Producing zero greenhouse gases','Balancing emitted greenhouse gases with equivalent removals','Reducing emissions by 50%','Using only renewable energy'], correctAnswer: 1, explanation: 'Net-zero means any CO₂ emitted is balanced by an equal amount removed from the atmosphere.', points: 10 },
      { question: 'Which of the following is a negative emission technology (NET)?', options: ['Solar panels','Wind turbines','Bioenergy with Carbon Capture and Storage (BECCS)','Electric vehicles'], correctAnswer: 2, explanation: 'BECCS burns bioenergy and captures the resulting CO₂, achieving negative net emissions.', points: 10 },
      { question: 'What is the Keeling Curve?', options: ['A graph showing ocean temperature rise','A long-term record of atmospheric CO₂ concentrations','A model predicting sea level rise','A formula for calculating carbon credits'], correctAnswer: 1, explanation: 'The Keeling Curve, started in 1958, is the longest continuous record of atmospheric CO₂ concentration.', points: 10 },
      { question: 'Pre-industrial CO₂ levels were approximately:', options: ['180 ppm','280 ppm','350 ppm','420 ppm'], correctAnswer: 1, explanation: 'Pre-industrial CO₂ was ~280 ppm. We have now exceeded 420 ppm — a 50% increase.', points: 10 },
      { question: 'What is "carbon budget" in climate science?', options: ['A government\'s spending on climate projects','Maximum cumulative CO₂ emissions to stay within a temperature limit','Corporate carbon offset credits','Annual national emission targets'], correctAnswer: 1, explanation: 'The carbon budget is the total amount of CO₂ that can be emitted while keeping warming below 1.5°C or 2°C.', points: 10 },
      { question: 'What is the "social cost of carbon" (SCC)?', options: ['Cost of installing solar panels per tonne of CO₂ avoided','Economic cost to society of emitting one additional tonne of CO₂','Price of carbon credits on the voluntary market','Cost of carbon capture technologies'], correctAnswer: 1, explanation: 'SCC is the estimated total economic damage from emitting one tonne of CO₂, including climate damages.', points: 10 },
      { question: 'Which ocean current system is at risk of collapse due to climate change?', options: ['El Niño Southern Oscillation','Atlantic Meridional Overturning Circulation (AMOC)','Pacific Decadal Oscillation','Indian Ocean Dipole'], correctAnswer: 1, explanation: 'AMOC (including the Gulf Stream) drives heat distribution in the Atlantic and is weakening due to freshwater from melting ice.', points: 10 },
      { question: 'What is "climate justice"?', options: ['Legal action against polluting companies','Recognition that climate impacts fall disproportionately on vulnerable communities','Equal energy pricing for all countries','Climate refugees seeking asylum'], correctAnswer: 1, explanation: 'Climate justice recognizes that those least responsible for emissions often suffer the worst impacts.', points: 10 },
      { question: 'Which country has the highest historical cumulative CO₂ emissions?', options: ['China','Russia','United States','European Union'], correctAnswer: 2, explanation: 'The USA has the highest cumulative historical emissions, having industrialized earliest and emitted heavily.', points: 10 },
      { question: 'What is permafrost thaw and why is it significant?', options: ['Melting of Arctic sea ice','Thawing of frozen soil releasing stored methane and CO₂','Warming of deep ocean waters','Melting of mountain glaciers causing floods'], correctAnswer: 1, explanation: 'Permafrost stores vast amounts of carbon. As it thaws, it releases CO₂ and methane — a dangerous feedback loop.', points: 10 },
      { question: 'What framework classifies countries\' emission reduction commitments under the Paris Agreement?', options: ['Carbon Trading System','Nationally Determined Contributions (NDCs)','Kyoto Protocol Annexes','IPCC Scenario Pathways'], correctAnswer: 1, explanation: 'NDCs are each country\'s self-determined climate targets, submitted to the UNFCCC and updated every 5 years.', points: 10 },
      { question: 'What is the albedo effect?', options: ['Reflection of sunlight back into space by bright surfaces','Absorption of heat by dark surfaces','Scattering of solar radiation by clouds','Greenhouse gas concentration effect'], correctAnswer: 0, explanation: 'Albedo is the fraction of solar energy reflected by a surface. Ice and snow have high albedo; oceans and forests have low albedo.', points: 10 },
      { question: 'Which greenhouse gas has the highest global warming potential over 20 years?', options: ['Carbon dioxide (CO₂)','Methane (CH₄)','Nitrous oxide (N₂O)','Sulphur hexafluoride (SF₆)'], correctAnswer: 3, explanation: 'SF₆ has a GWP of ~23,500 over 100 years, making it the most potent greenhouse gas by weight.', points: 10 },
      { question: 'What is "loss and damage" in UNFCCC negotiations?', options: ['Economic losses from transitioning to renewables','Compensation for climate impacts that cannot be adapted to','Damage from extreme weather unrelated to climate','Loss of biodiversity due to deforestation'], correctAnswer: 1, explanation: 'Loss and damage refers to irreversible harm from climate change that goes beyond adaptation — a key issue for vulnerable nations.', points: 10 },
      { question: 'What percentage of global emissions come from food systems (agriculture, land use, food chain)?', options: ['About 5%','About 15%','About 26-30%','About 50%'], correctAnswer: 2, explanation: 'Food systems account for ~26-30% of global GHG emissions including agriculture, livestock, deforestation, and food waste.', points: 10 },
    ],
  },
  {
    title: 'Circular Economy & Sustainable Consumption (College)',
    description: 'Life cycle analysis, circular economy, EPR, sustainable production and consumption systems',
    topic: 'recycling', difficulty: 'intermediate', thumbnail: '♻️',
    xpReward: 100, timeLimit: 900, targetAudience: 'College Student',
    questions: [
      { question: 'What is the core principle of a "circular economy"?', options: ['Maximizing production output','Eliminating waste by keeping resources in use as long as possible','Using only natural materials','Reducing international trade'], correctAnswer: 1, explanation: 'A circular economy aims to eliminate waste by designing products for reuse, repair, and recycling.', points: 10 },
      { question: 'What does Life Cycle Assessment (LCA) measure?', options: ['How long a product lasts','Environmental impacts of a product from raw material extraction to disposal','The cost of recycling a product','Consumer satisfaction with eco-products'], correctAnswer: 1, explanation: 'LCA evaluates total environmental impacts throughout a product\'s entire life: production, use, and end-of-life.', points: 10 },
      { question: 'Extended Producer Responsibility (EPR) policies require:', options: ['Consumers to return products','Governments to fund all recycling','Manufacturers to manage their products at end-of-life','Retailers to provide free recycling bins'], correctAnswer: 2, explanation: 'EPR shifts responsibility for post-consumer waste management to the product manufacturer.', points: 10 },
      { question: 'What is "greenwashing"?', options: ['Cleaning products with eco-friendly chemicals','Making misleading environmental claims to appear sustainable','Painting factories green','A type of agricultural technique'], correctAnswer: 1, explanation: 'Greenwashing is when companies make false or exaggerated environmental claims to deceive consumers.', points: 10 },
      { question: 'Which material has the highest environmental cost to produce but can be infinitely recycled?', options: ['Plastic (PET)','Aluminum','Glass','Cardboard'], correctAnswer: 1, explanation: 'Aluminum production is energy-intensive, but recycling it uses only 5% of the energy of virgin production.', points: 10 },
      { question: 'What is the "cradle-to-cradle" design philosophy?', options: ['Products designed to last until they reach a landfill','Products designed so all materials can be continuously recycled or safely returned to nature','Products designed for maximum durability','Products designed to be incinerated cleanly'], correctAnswer: 1, explanation: 'Cradle-to-cradle means products are designed so materials cycle endlessly in either technical or biological loops.', points: 10 },
      { question: 'The UN Sustainable Development Goal 12 focuses on:', options: ['Clean water and sanitation','Responsible consumption and production','Climate action','Zero hunger'], correctAnswer: 1, explanation: 'SDG 12 calls for sustainable consumption and production patterns, including waste reduction and efficient resource use.', points: 10 },
      { question: 'What is a "material passport"?', options: ['A certificate for importing raw materials','A digital document recording a product\'s material composition for future recycling','A border control system for hazardous waste','A label showing a product\'s carbon footprint'], correctAnswer: 1, explanation: 'Material passports store data about a product\'s materials, making future disassembly and recycling far more efficient.', points: 10 },
      { question: 'What is "industrial symbiosis"?', options: ['Two competing industries sharing workers','Businesses exchanging waste and by-products so one\'s waste becomes another\'s resource','Government regulation of industrial pollution','Joint marketing by eco-friendly companies'], correctAnswer: 1, explanation: 'Industrial symbiosis creates networks where waste/by-products from one company become raw materials for another.', points: 10 },
      { question: 'The "reduce, reuse, recycle" hierarchy prioritizes in which order?', options: ['Recycle first, then reuse, then reduce','All three are equally important','Reduce is most important, then reuse, then recycle','Reuse is most important, then recycle, then reduce'], correctAnswer: 2, explanation: 'Reducing is the most impactful as it prevents waste entirely; reuse extends product life; recycling recovers materials.', points: 10 },
      { question: 'What percentage of plastic waste has been recycled globally since plastic production began?', options: ['About 50%','About 30%','About 15%','About 9%'], correctAnswer: 3, explanation: 'Only about 9% of all plastic ever produced has been recycled; 12% was incinerated and 79% went to landfill or the environment.', points: 10 },
      { question: 'What is "planned obsolescence"?', options: ['Products designed to break or become outdated to drive repurchases','A recycling technology for electronics','A sustainable manufacturing standard','A government policy on product lifetimes'], correctAnswer: 0, explanation: 'Planned obsolescence is a design strategy where products become obsolete faster than necessary, driving more consumption.', points: 10 },
      { question: 'The "right to repair" movement advocates for:', options: ['Free repair services for all','Consumers\' legal right to repair their own products and access spare parts','Companies being forced to repair products for free','Government-funded repair shops'], correctAnswer: 1, explanation: 'Right to repair demands that manufacturers provide manuals, spare parts, and tools so consumers can fix their own devices.', points: 10 },
      { question: 'What is "upcycling" in the context of circular economy?', options: ['Sending waste to a more advanced recycling facility','Converting waste into materials or products of higher value or quality','Transporting recyclables to higher-capacity plants','Upgrading recycling technology'], correctAnswer: 1, explanation: 'Upcycling converts waste into something of higher quality or value, unlike downcycling where quality is reduced.', points: 10 },
      { question: 'Which country has the highest recycling rate globally?', options: ['Germany','Japan','South Korea','Sweden'], correctAnswer: 0, explanation: 'Germany consistently leads with ~65%+ recycling rates, driven by strict EPR laws and strong consumer behaviour.', points: 10 },
      { question: 'What is a "product stewardship" programme?', options: ['Quality control in manufacturing','Shared responsibility between producers, retailers, and consumers for a product\'s environmental impact','Government inspection of factories','A label certifying eco-friendly products'], correctAnswer: 1, explanation: 'Product stewardship distributes environmental responsibility across the product chain — from design to disposal.', points: 10 },
      { question: 'What does the term "zero waste to landfill" mean for a company?', options: ['Producing no waste at all','Diverting all operational waste from landfill through recycling, composting, or energy recovery','Sending all waste for incineration','Reducing waste by 100% through efficiency'], correctAnswer: 1, explanation: 'Zero waste to landfill means companies divert 100% of waste through alternative routes — not eliminating waste entirely.', points: 10 },
      { question: 'What is "bioeconomy"?', options: ['Economic growth in biological research sectors','An economy based on the production and use of biological resources and processes','Organic farming subsidies','The market for biodegradable packaging'], correctAnswer: 1, explanation: 'Bioeconomy uses renewable biological resources (plants, animals, microbes) as the basis for sustainable production.', points: 10 },
      { question: 'Which international framework sets global targets for reducing food waste?', options: ['Paris Agreement','Montreal Protocol','UN SDG Target 12.3','Basel Convention'], correctAnswer: 2, explanation: 'SDG Target 12.3 calls for halving per capita global food waste at retail and consumer levels by 2030.', points: 10 },
      { question: 'What is "dematerialization" in sustainable economics?', options: ['Converting physical goods to digital products','Reducing the total quantity of materials used to deliver the same economic output','Removing materials from landfill sites','A type of chemical recycling process'], correctAnswer: 1, explanation: 'Dematerialization is achieving more economic value while using fewer physical resources — essential for sustainability.', points: 10 },
    ],
  },
  {
    title: 'Biodiversity Conservation & Ecology (College)',
    description: 'Ecosystem services valuation, IUCN metrics, conservation biology and biodiversity frameworks',
    topic: 'biodiversity', difficulty: 'intermediate', thumbnail: '🦋',
    xpReward: 100, timeLimit: 900, targetAudience: 'College Student',
    questions: [
      { question: 'Which framework classifies ecosystem services into provisioning, regulating, cultural, and supporting?', options: ['IUCN Red List','Millennium Ecosystem Assessment','Convention on Biological Diversity','IPBES Global Assessment'], correctAnswer: 1, explanation: 'The Millennium Ecosystem Assessment (2005) established this widely-used classification of ecosystem services.', points: 10 },
      { question: 'What is the "6th mass extinction" referring to?', options: ['A Hollywood film','The current rapid loss of species driven by human activities','The extinction of dinosaurs','A future predicted event'], correctAnswer: 1, explanation: 'Scientists call our current biodiversity crisis the 6th mass extinction — the first caused primarily by humans.', points: 10 },
      { question: 'What does "HIPPO" stand for in conservation biology threats?', options: ['An endangered mammal','Habitat loss, Invasive species, Pollution, Population growth, Overhunting','High Impact Protected Priority Operations','Hydrology, Insects, Plants, Predators, Omnivores'], correctAnswer: 1, explanation: 'HIPPO represents the five main threats to biodiversity: Habitat, Invasive species, Pollution, Population, Overhunting.', points: 10 },
      { question: 'The Kunming-Montreal Global Biodiversity Framework\'s "30x30" target means:', options: ['Reduce extinction rate by 30% by 2030','Protect 30% of land and ocean by 2030','Plant 30 billion trees by 2030','Reduce deforestation by 30% in 30 years'], correctAnswer: 1, explanation: 'The 30x30 target commits nations to protecting 30% of land and marine areas by 2030.', points: 10 },
      { question: 'Which ecosystem has the highest biodiversity per unit area on Earth?', options: ['Temperate forest','Arctic tundra','Tropical rainforest','Ocean deep sea'], correctAnswer: 2, explanation: 'Tropical rainforests cover ~6% of Earth\'s surface but harbor over 50% of known species.', points: 10 },
      { question: 'What is the IUCN Red List criteria for "Critically Endangered"?', options: ['Population reduced by 10% in 10 years','Population reduced by ≥80% in 10 years or 3 generations','Fewer than 10,000 mature individuals remain','Species found in only one country'], correctAnswer: 1, explanation: 'Critically Endangered (CR) requires ≥80% population reduction over 10 years or 3 generations.', points: 10 },
      { question: 'What is "keystone species" theory?', options: ['Species most numerous in an ecosystem','Species that has disproportionately large effect on ecosystem relative to its abundance','Apex predators at the top of food chains','Species unique to one geographic location'], correctAnswer: 1, explanation: 'Keystone species have outsized ecosystem impacts. Removing them causes dramatic changes — e.g., wolves in Yellowstone.', points: 10 },
      { question: 'What is habitat fragmentation and why is it harmful?', options: ['Complete destruction of a habitat','Breaking a continuous habitat into smaller, isolated patches, reducing species movement and gene flow','Seasonal changes in habitat availability','Gradual degradation of habitat quality over time'], correctAnswer: 1, explanation: 'Fragmentation isolates populations, reduces genetic diversity, increases extinction risk and disrupts ecological processes.', points: 10 },
      { question: 'What is "rewilding" in conservation?', options: ['Introducing exotic animals to new regions','Large-scale restoration of ecosystems and reintroduction of native species to restore natural processes','Breeding endangered species in captivity','Protecting existing wilderness areas from human access'], correctAnswer: 1, explanation: 'Rewilding restores natural processes, often through reintroducing lost species like wolves or beavers to regulate ecosystems.', points: 10 },
      { question: 'What does CITES regulate?', options: ['Carbon emissions trading between countries','International trade in endangered species of wild fauna and flora','Climate adaptation funding for developing countries','Conservation standards for protected areas'], correctAnswer: 1, explanation: 'CITES (Convention on International Trade in Endangered Species) controls trade to prevent over-exploitation of wildlife.', points: 10 },
      { question: 'What is alpha diversity?', options: ['Number of species across a landscape','Number of species within a local community or habitat','Variation in species composition between habitats','Total species richness across a region'], correctAnswer: 1, explanation: 'Alpha diversity measures species richness within a single ecosystem or habitat patch.', points: 10 },
      { question: 'What are "ecosystem engineers"?', options: ['Environmental consultants designing ecosystems','Species that physically modify habitats, creating conditions for other species','Ecologists who model biodiversity','Government officials managing national parks'], correctAnswer: 1, explanation: 'Ecosystem engineers like beavers and elephants physically modify environments, creating habitats for many other species.', points: 10 },
      { question: 'What is the "extinction debt" concept?', options: ['Financial cost of preventing extinctions','Species committed to extinction due to past habitat loss but not yet gone','Debt owed by countries for causing extinctions','Carbon debt caused by species loss'], correctAnswer: 1, explanation: 'Extinction debt: species can persist temporarily after habitat loss but are "committed" to future extinction.', points: 10 },
      { question: 'Which biome stores the most carbon per unit area?', options: ['Tropical rainforest','Temperate grassland','Peatland/bog','Coral reef'], correctAnswer: 2, explanation: 'Peatlands store ~550 billion tonnes of carbon — twice that of all forests combined — despite covering only 3% of land.', points: 10 },
      { question: 'What is "biophilia"?', options: ['The study of biological diversity','An innate human affinity for and connection with other living systems','Farming using biological pest control','The economic value of ecosystem services'], correctAnswer: 1, explanation: 'Biophilia, proposed by E.O. Wilson, describes humans\' evolutionary bond with and need for connection to nature.', points: 10 },
      { question: 'What is the "trophic cascade" effect?', options: ['Nutrients moving from land to ocean','Changes at one trophic level causing ripple effects throughout the food web','Seasonal migration patterns of apex predators','Decomposition of organic matter through food chain'], correctAnswer: 1, explanation: 'Trophic cascades occur when apex predators regulate prey, which regulates vegetation — e.g., wolf reintroduction in Yellowstone.', points: 10 },
      { question: 'What is "in situ" conservation?', options: ['Conservation in zoos and botanical gardens','Conservation of species in their natural habitats','Conservation using DNA banking','Conservation through international law'], correctAnswer: 1, explanation: 'In situ conservation protects species in their natural habitats — considered the most effective approach.', points: 10 },
      { question: 'Which ocean zone has the highest primary productivity?', options: ['The deep abyssal zone','The continental shelf zone','The open ocean epipelagic zone','The intertidal zone'], correctAnswer: 1, explanation: 'Continental shelves are shallow and nutrient-rich (from river runoff), supporting the highest marine productivity.', points: 10 },
      { question: 'What is environmental DNA (eDNA) used for?', options: ['Modifying crop genetics','Detecting species presence in an environment from DNA fragments they leave behind','Cloning endangered species','Analyzing soil composition'], correctAnswer: 1, explanation: 'eDNA allows scientists to detect species presence from water or soil samples without physically observing the animal.', points: 10 },
      { question: 'What does the "species-area relationship" predict?', options: ['Species travel farther in larger habitats','Larger habitat areas support exponentially more species','All species require the same minimum area','Island species are more diverse than mainland species'], correctAnswer: 1, explanation: 'The species-area relationship shows that doubling habitat area increases species richness by approximately 20-25%.', points: 10 },
    ],
  },
  {
    title: 'Marine Science & Ocean Systems (College)',
    description: 'Ocean acidification, marine law, fisheries management, blue carbon and marine pollution',
    topic: 'oceanHealth', difficulty: 'intermediate', thumbnail: '🐋',
    xpReward: 100, timeLimit: 900, targetAudience: 'College Student',
    questions: [
      { question: 'What is "ocean acidification" measured by?', options: ['Increase in salt concentration','Decrease in pH due to CO₂ absorption','Rise in sea surface temperature','Decrease in dissolved oxygen'], correctAnswer: 1, explanation: 'Ocean pH has decreased from ~8.2 to ~8.1 since industrialization as oceans absorb CO₂ forming carbonic acid.', points: 10 },
      { question: 'What are "blue carbon" ecosystems?', options: ['Deep ocean trenches','Coastal ecosystems like mangroves, seagrasses, and salt marshes that store carbon','Arctic ocean ecosystems','Bioluminescent marine organisms'], correctAnswer: 1, explanation: 'Blue carbon ecosystems sequester carbon at rates up to 10x higher than terrestrial forests per unit area.', points: 10 },
      { question: 'UNCLOS defines the Exclusive Economic Zone (EEZ) as extending:', options: ['12 nautical miles from shore','200 nautical miles from shore','500 nautical miles from shore','Halfway between two countries'], correctAnswer: 1, explanation: 'Under UNCLOS, coastal states have sovereign rights over natural resources in a 200 nautical mile EEZ.', points: 10 },
      { question: 'What is maximum sustainable yield (MSY) in fisheries management?', options: ['Maximum number of fish that can be caught','Largest harvest maintaining a population\'s ability to replenish itself','Minimum catch required for profitable fishing','Total weight of fish in an ocean'], correctAnswer: 1, explanation: 'MSY is the highest harvest that maintains population equilibrium — exceeding it causes population collapse.', points: 10 },
      { question: 'Dead zones in the ocean are primarily caused by:', options: ['Nuclear radiation','Agricultural runoff causing eutrophication and oxygen depletion','Oil spills','Deep sea mining'], correctAnswer: 1, explanation: 'Fertilizer runoff causes algal blooms; decomposing algae depletes oxygen, creating hypoxic "dead zones".', points: 10 },
      { question: 'What is ocean stratification and why does it matter?', options: ['Division of oceans into fishing zones','Layering of ocean water by temperature and salinity, limiting nutrient exchange','Classification of ocean species by depth','Monitoring ocean pollution from satellites'], correctAnswer: 1, explanation: 'Warming increases stratification, reducing nutrient upwelling to surface waters, thereby decreasing ocean productivity.', points: 10 },
      { question: 'What is the "biological pump" in the ocean?', options: ['Mechanical pumps used in desalination','Process by which marine organisms absorb CO₂ and transport carbon to the deep ocean','Water circulation driven by temperature differences','Ocean current system driven by wind'], correctAnswer: 1, explanation: 'The biological pump is when marine organisms absorb surface CO₂ through photosynthesis; when they die they sink, sequestering carbon.', points: 10 },
      { question: 'What are microplastics and what is their primary threat?', options: ['Plastic pieces smaller than 5mm that contaminate food chains and organisms','Plastic bags that block sunlight in the ocean','Microorganisms that produce plastic-like compounds','Tiny plastic particles used in medicine'], correctAnswer: 0, explanation: 'Microplastics (< 5mm) enter food chains, carry toxins, damage internal organs and have been found in human blood.', points: 10 },
      { question: 'What is bycatch in commercial fishing?', options: ['The total intended catch of a fishing vessel','Unintended capture of non-target species including dolphins, turtles and seabirds','Fish caught using bait rather than nets','Fish caught in excess of the quota'], correctAnswer: 1, explanation: 'Bycatch kills millions of non-target animals annually, driving population declines of many marine species.', points: 10 },
      { question: 'What percentage of Earth\'s oxygen is produced by phytoplankton?', options: ['10%','30%','About 50%','70%'], correctAnswer: 2, explanation: 'Marine phytoplankton are responsible for producing approximately 50% of Earth\'s oxygen through photosynthesis.', points: 10 },
      { question: 'What is the "thermocline"?', options: ['A measurement of ocean heat content','A sharp layer in the ocean where temperature drops rapidly with depth','The boundary between ocean and atmosphere','The warmest layer of the ocean'], correctAnswer: 1, explanation: 'The thermocline is the zone where temperature drops sharply with depth, separating warm surface water from cold deep water.', points: 10 },
      { question: 'What is deep sea mining and what is the primary concern?', options: ['Oil drilling in shallow coastal waters','Extraction of mineral nodules from the ocean floor that disrupts fragile deep-sea ecosystems','Dredging sand from the seabed for construction','Removing shipwreck debris from the ocean floor'], correctAnswer: 1, explanation: 'Deep sea mining targets polymetallic nodules but destroys slow-recovering deep-sea ecosystems and creates sediment plumes.', points: 10 },
      { question: 'What causes the ENSO (El Niño-Southern Oscillation) climate pattern?', options: ['Changes in Earth\'s orbit','Variations in sea surface temperature in the tropical Pacific affecting global weather','Solar radiation cycles','Underwater volcanic activity'], correctAnswer: 1, explanation: 'ENSO alternates between El Niño (warm Pacific) and La Niña (cool Pacific), affecting rainfall and temperature worldwide.', points: 10 },
      { question: 'What is coral symbiosis and why does it matter for reef health?', options: ['Coral competing with algae for space','Coral hosting zooxanthellae algae that provide 90% of coral\'s energy through photosynthesis','Coral cleaning fish that live in them','Coral reproducing through fragmentation'], correctAnswer: 1, explanation: 'Zooxanthellae live in coral tissue, providing up to 90% of energy via photosynthesis. Bleaching expels them, starving the coral.', points: 10 },
      { question: 'What is the "high seas" under international law?', options: ['Territorial waters beyond 12 nautical miles','Ocean areas beyond national jurisdiction, covering ~60% of the ocean surface','Areas of the ocean above 1000m depth','Marine protected areas in international waters'], correctAnswer: 1, explanation: 'High seas are beyond any national jurisdiction and cover ~60% of oceans — historically unprotected but now governed by the BBNJ Treaty.', points: 10 },
      { question: 'What does "trawling" refer to and what is its environmental impact?', options: ['Surface fishing using floating nets','Dragging weighted nets along the seafloor, destroying benthic habitats','Fishing using sonar to locate fish schools','Line fishing in open ocean'], correctAnswer: 1, explanation: 'Bottom trawling destroys seafloor habitats like corals and sea grass beds, catching everything in its path.', points: 10 },
      { question: 'What is the Sargasso Sea notable for?', options: ['Having the world\'s largest coral reef','Being the only sea defined by ocean currents, not land boundaries, and habitat for unique sargassum algae','Being the deepest point in all oceans','Being entirely enclosed by the European continent'], correctAnswer: 1, explanation: 'The Sargasso Sea is unique — bounded by four ocean currents, it hosts floating sargassum seaweed crucial for many species.', points: 10 },
      { question: 'What is ocean thermal energy conversion (OTEC)?', options: ['Measuring ocean heat for climate modelling','Technology using temperature difference between warm surface and cold deep water to generate electricity','Solar panels floating on ocean surfaces','Tidal power using ocean current movement'], correctAnswer: 1, explanation: 'OTEC exploits the temperature gradient between warm surface (25°C+) and cold deep ocean water (5°C) to produce clean electricity.', points: 10 },
      { question: 'What is the primary cause of sea level rise today?', options: ['Tectonic plate movement','Roughly equally from thermal expansion of ocean water and melting ice','Only from melting glaciers and ice sheets','Changes in ocean salinity'], correctAnswer: 1, explanation: 'Sea level rise is currently driven roughly equally by thermal expansion of warming oceans (~50%) and ice sheet/glacier melt (~50%).', points: 10 },
      { question: 'What is bioaccumulation in marine food webs?', options: ['Growth of coral reefs over time','Progressive increase in concentration of toxins in organisms at each trophic level','Natural decomposition of organic matter in sediment','Accumulation of nutrients in coastal zones'], correctAnswer: 1, explanation: 'Bioaccumulation (biomagnification) concentrates toxins like mercury and PCBs up the food chain, making apex predators most toxic.', points: 10 },
    ],
  },
  {
    title: 'Energy Systems & Sustainability Policy (College)',
    description: 'Energy transition, grid integration, LCOE, energy justice, and international climate finance',
    topic: 'renewableEnergy', difficulty: 'intermediate', thumbnail: '⚡',
    xpReward: 100, timeLimit: 900, targetAudience: 'College Student',
    questions: [
      { question: 'What is LCOE (Levelized Cost of Energy)?', options: ['Cost of building one wind turbine','Average net present cost of electricity generation over a plant\'s lifetime','Annual subsidy given to renewable energy','Cost of connecting renewables to the grid'], correctAnswer: 1, explanation: 'LCOE provides a standardized metric to compare different electricity generation technologies over their lifetime.', points: 10 },
      { question: 'What is the "duck curve" problem in grid management?', options: ['Shape of wind turbine blades','Mismatch between peak solar generation and peak demand creating grid instability','A type of wave energy converter','The declining cost curve of renewables'], correctAnswer: 1, explanation: 'The duck curve shows how midday solar overproduction and evening demand spikes create grid management challenges.', points: 10 },
      { question: 'Which technology is considered most promising for long-duration energy storage?', options: ['Lithium-ion batteries','Pumped hydro storage','Lead-acid batteries','Supercapacitors'], correctAnswer: 1, explanation: 'Pumped hydro provides ~94% of global energy storage capacity and is best suited for long-duration storage.', points: 10 },
      { question: 'What does "grid parity" mean for renewable energy?', options: ['When renewables match fossil fuel reliability','When cost of renewable electricity equals conventional grid electricity','Equal distribution of renewable plants globally','When all countries agree on renewable standards'], correctAnswer: 1, explanation: 'Grid parity is when renewables generate electricity at the same or lower cost as conventional sources — now achieved by solar and wind.', points: 10 },
      { question: 'What is "energy poverty"?', options: ['Countries lacking fossil fuel reserves','Lack of access to affordable, reliable, sustainable and modern energy','High energy prices for renewable users','Dependence on imported energy sources'], correctAnswer: 1, explanation: 'Energy poverty affects ~770 million people globally, limiting economic development and forcing use of polluting energy.', points: 10 },
      { question: 'What is a power purchase agreement (PPA) in renewable energy?', options: ['Government subsidy for solar panel installation','Long-term contract between an energy buyer and renewable energy producer','Permit required to build wind farms','Agreement between countries on energy imports'], correctAnswer: 1, explanation: 'PPAs allow buyers (governments, corporations) to purchase renewable energy at fixed prices, providing long-term revenue certainty for developers.', points: 10 },
      { question: 'What is "curtailment" in electricity grid management?', options: ['Reducing electricity demand through efficiency','Intentionally reducing output of power plants when supply exceeds demand','Cutting electricity supply to certain areas','Phasing out fossil fuel plants'], correctAnswer: 1, explanation: 'Curtailment occurs when too much electricity (often from wind/solar) is being generated for the grid to absorb.', points: 10 },
      { question: 'What is the capacity factor of a power plant?', options: ['Maximum power a plant can produce','Ratio of actual energy output to maximum possible output over a time period','Efficiency of converting fuel to electricity','Cost per megawatt of installed capacity'], correctAnswer: 1, explanation: 'Capacity factor measures how often a plant runs at full capacity. Solar averages ~15-25%; wind ~25-45%; nuclear ~90%.', points: 10 },
      { question: 'What is "green hydrogen" and how is it produced?', options: ['Hydrogen mixed with methane for cleaner combustion','Hydrogen produced by electrolysis of water using renewable electricity','Hydrogen extracted from plant biomass','Hydrogen captured from industrial processes'], correctAnswer: 1, explanation: 'Green hydrogen is produced by splitting water using renewable electricity — producing zero CO₂, unlike "grey" hydrogen from natural gas.', points: 10 },
      { question: 'What is the Global South\'s primary argument regarding climate finance?', options: ['Developing countries should fund their own transitions','Developed countries that caused most historical emissions should fund developing nations\' clean energy transitions','All countries should contribute equally to climate funds','Technology transfer is more important than financial aid'], correctAnswer: 1, explanation: 'Climate justice demands that historically high-emitting wealthy nations finance clean energy transitions in countries that contributed least to the problem.', points: 10 },
      { question: 'What is "demand-side management" in energy systems?', options: ['Managing energy supply from multiple sources','Strategies to modify consumer demand patterns to reduce peak loads and overall consumption','Government control of energy prices','Management of energy infrastructure by grid operators'], correctAnswer: 1, explanation: 'Demand-side management uses incentives, pricing, and efficiency to reduce or shift energy consumption, reducing the need for additional generation.', points: 10 },
      { question: 'What is the "energy trilemma"?', options: ['Three types of fossil fuels','Balancing energy security, equity (affordability), and environmental sustainability','Conflict between coal, oil and gas industries','Three phases of energy production: generation, transmission, distribution'], correctAnswer: 1, explanation: 'The energy trilemma requires simultaneously achieving energy security, affordability, and environmental sustainability — often in tension.', points: 10 },
      { question: 'What is "net metering" in solar energy policy?', options: ['Measuring energy consumption by building','Policy allowing solar panel owners to sell excess electricity back to the grid at retail price','Monitoring net carbon emissions from solar manufacturing','Calculating net energy output over a solar panel\'s lifetime'], correctAnswer: 1, explanation: 'Net metering credits solar owners for electricity exported to the grid, effectively running the electricity meter backwards.', points: 10 },
      { question: 'What is a "carbon border adjustment mechanism" (CBAM)?', options: ['A tax on domestic carbon emissions','A tariff on imported goods based on their carbon footprint to prevent carbon leakage','A technical standard for low-carbon manufacturing','A certification system for carbon-neutral products'], correctAnswer: 1, explanation: 'The EU\'s CBAM ensures imported goods face the same carbon costs as EU products, preventing industries from relocating to avoid carbon pricing.', points: 10 },
      { question: 'What is the "just transition" concept in energy policy?', options: ['A rapid switch to renewables regardless of social impacts','Ensuring the shift to clean energy is fair and creates opportunities for affected workers and communities','A legal framework for energy transition financing','International agreement on equitable renewable energy distribution'], correctAnswer: 1, explanation: 'Just transition ensures that workers in fossil fuel industries and vulnerable communities are supported and benefit from the clean energy shift.', points: 10 },
      { question: 'What is "peaker plant" in electricity systems?', options: ['The largest baseload power station in a grid','Power plants used only during periods of peak electricity demand, typically running on natural gas','First power plant built in a region','Renewable energy plant with highest capacity factor'], correctAnswer: 1, explanation: 'Peaker plants run only during high-demand periods, are expensive to operate and are a key target for replacement by batteries and demand response.', points: 10 },
      { question: 'What is the significance of the "learning rate" in renewable energy economics?', options: ['How quickly engineers learn to maintain turbines','The percentage cost reduction for each doubling of cumulative installed capacity','Rate at which renewable energy is adopted globally','Speed at which new renewable technologies are developed'], correctAnswer: 1, explanation: 'Learning rates (solar: ~20% cost reduction per doubling) explain why renewable costs have fallen dramatically with scale.', points: 10 },
      { question: 'What is "vehicle to grid" (V2G) technology?', options: ['Technology for self-driving electric vehicles','Using electric vehicles\' batteries to supply electricity back to the grid during peak demand','Wireless charging for electric vehicles','Electric vehicle software updates via internet'], correctAnswer: 1, explanation: 'V2G allows EV batteries to act as distributed storage, supplying grid power when demand is high and charging when supply is abundant.', points: 10 },
      { question: 'What is the main challenge of integrating large amounts of solar PV into electricity grids?', options: ['Solar panels are too expensive to maintain','Solar output is intermittent and doesn\'t always match demand patterns, requiring storage or flexible backup','Solar panels have too short a lifespan','Solar energy cannot be transmitted over long distances'], correctAnswer: 1, explanation: 'Solar\'s variability (day/night, weather) creates grid balancing challenges, requiring storage, demand flexibility or backup generation.', points: 10 },
      { question: 'What does "decarbonization" of the energy sector mean?', options: ['Removing carbon from fossil fuels before burning','Progressively eliminating greenhouse gas emissions from energy production and use','Carbon capture and storage at power plants','Replacing coal with natural gas as a transition fuel'], correctAnswer: 1, explanation: 'Energy sector decarbonization means shifting to zero-carbon electricity generation and electrifying heat and transport to eliminate fossil fuels.', points: 10 },
    ],
  },
];

const challenges = [
  { title: 'Daily Quiz Champion', description: 'Complete any quiz today to earn bonus XP!', type: 'daily', category: 'quiz', topic: 'general', xpReward: 25, icon: '📝', requirement: { action: 'complete_quiz', value: 1 } },
  { title: 'Weekend Eco Explorer', description: 'Complete 3 quizzes this weekend', type: 'weekly', category: 'quiz', topic: 'general', xpReward: 75, icon: '🌿', requirement: { action: 'complete_quiz', value: 3 } },
  { title: 'Climate Crusader', description: 'Master the Climate Change quiz with 80%+ score', type: 'weekly', category: 'quiz', topic: 'climateChange', xpReward: 100, icon: '🌡️', requirement: { action: 'quiz_score', value: 80 } },
  { title: 'Ocean Guardian', description: 'Complete the Ocean Health quiz', type: 'daily', category: 'quiz', topic: 'oceanHealth', xpReward: 35, icon: '🌊', requirement: { action: 'complete_quiz', value: 1 } },
  { title: 'Streak Keeper', description: 'Log in 5 days in a row', type: 'weekly', category: 'learning', topic: 'general', xpReward: 60, icon: '🔥', requirement: { action: 'maintain_streak', value: 5 } },
  { title: 'Recycling Rookie', description: 'Complete the Recycling quiz', type: 'daily', category: 'quiz', topic: 'recycling', xpReward: 30, icon: '♻️', requirement: { action: 'complete_quiz', value: 1 } },
  { title: 'Biodiversity Scholar', description: 'Score 90%+ on the Biodiversity quiz', type: 'weekly', category: 'quiz', topic: 'biodiversity', xpReward: 120, icon: '🦋', requirement: { action: 'quiz_score', value: 90 } },
  { title: 'Energy Pioneer', description: 'Complete the Renewable Energy quiz', type: 'daily', category: 'quiz', topic: 'renewableEnergy', xpReward: 40, icon: '⚡', requirement: { action: 'complete_quiz', value: 1 } },
];

const missions = [
  { title: 'Zero Plastic Week', description: 'Challenge yourself to reduce single-use plastic for one full week.', topic: 'recycling', difficulty: 'beginner', icon: '♻️', totalXpReward: 150,
    steps: [
      { order: 1, title: 'Learn about plastic pollution', description: 'Complete the Recycling quiz to understand plastic\'s impact.', type: 'quiz', xpReward: 30 },
      { order: 2, title: 'Log a recycling activity', description: 'Submit a real-world activity showing you recycled or reduced plastic use.', type: 'activity', xpReward: 40 },
      { order: 3, title: 'Spread awareness', description: 'Log an awareness activity — share what you learned about plastic with someone.', type: 'activity', xpReward: 40 },
      { order: 4, title: 'Final reflection', description: 'Complete the Ocean Health quiz to see how plastic affects marine ecosystems.', type: 'quiz', xpReward: 40 },
    ],
  },
  { title: 'Climate Action Hero', description: 'Understand climate change deeply and take real actions to reduce your carbon footprint.', topic: 'climateChange', difficulty: 'intermediate', icon: '🌡️', totalXpReward: 200,
    steps: [
      { order: 1, title: 'Climate fundamentals', description: 'Complete the Climate Change quiz.', type: 'quiz', xpReward: 40 },
      { order: 2, title: 'Energy saving action', description: 'Submit a real-world activity showing you saved energy at home or school.', type: 'activity', xpReward: 50 },
      { order: 3, title: 'Renewable energy deep dive', description: 'Complete the Renewable Energy quiz.', type: 'quiz', xpReward: 40 },
      { order: 4, title: 'Carbon reduction action', description: 'Log a meaningful carbon-reducing activity.', type: 'activity', xpReward: 70 },
    ],
  },
  { title: 'Biodiversity Champion', description: 'Explore local ecosystems and contribute to biodiversity preservation.', topic: 'biodiversity', difficulty: 'advanced', icon: '🦋', totalXpReward: 250,
    steps: [
      { order: 1, title: 'Study biodiversity', description: 'Complete the Biodiversity quiz.', type: 'quiz', xpReward: 50 },
      { order: 2, title: 'Local species observation', description: 'Log an activity where you observed and documented local wildlife or plants.', type: 'activity', xpReward: 60 },
      { order: 3, title: 'Tree planting or clean-up', description: 'Participate in tree planting or a nature clean-up and submit evidence.', type: 'activity', xpReward: 80 },
      { order: 4, title: 'Ocean connection', description: 'Complete the Ocean Health quiz to understand aquatic biodiversity.', type: 'quiz', xpReward: 60 },
    ],
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/ecoquest');
    console.log('Connected to MongoDB');
    await Promise.all([Badge.deleteMany({}), Quiz.deleteMany({}), Challenge.deleteMany({}), Mission.deleteMany({})]);
    console.log('Cleared existing data');

    await Badge.insertMany(badges);
    console.log(`✅ Seeded ${badges.length} badges`);

    const allQuizzes = [...schoolQuizzes, ...collegeQuizzes];
    await Quiz.insertMany(allQuizzes);
    console.log(`✅ Seeded ${schoolQuizzes.length} school quizzes (10 questions each)`);
    console.log(`✅ Seeded ${collegeQuizzes.length} college quizzes (20 questions each)`);

    await Challenge.insertMany(challenges);
    console.log(`✅ Seeded ${challenges.length} challenges`);

    await Mission.insertMany(missions);
    console.log(`✅ Seeded ${missions.length} missions`);

    // Admin
    if (!await User.findOne({ email: 'ecoquestadmin@gmail.com' })) {
      await User.create({ username: 'EcoAdmin', email: 'ecoquestadmin@gmail.com', password: 'Admin123!', role: 'admin', avatar: '🌳', xp: 9999, level: 9, studentType: 'Teacher', institution: 'EcoQuest HQ' });
      console.log('✅ Admin: ecoquestadmin@gmail.com / Admin123!');
    }
    // Demo teacher
    if (!await User.findOne({ email: 'teacher@gmail.com' })) {
      await User.create({ username: 'EcoTeacher', email: 'teacher@gmail.com', password: 'Teacher123!', role: 'teacher', avatar: '🎓', xp: 0, level: 1, studentType: 'Teacher', institution: 'Lovely Professional University' });
      console.log('✅ Teacher: teacher@gmail.com / Teacher123!');
    }

    console.log('\n🌱 Database seeded successfully!');
    console.log('📚 School quizzes: 10 questions each (5 quizzes × topics)');
    console.log('🎓 College quizzes: 20 questions each (5 quizzes × topics)');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err);
    process.exit(1);
  }
}
seed();
